[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 120
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = [
	"ERA001", # commented-out-code
	"YTT", 
	"ANN",
	"S",
	"F",
	"W",
	"E",
	"C90",
	"I",
	"N",
	"D",
	"UP",
	"ASYNC",
	"TRIO",
	"BLE",
	"FBT",
	"B",
	"A",
	"COM",
	"C4",
	"DTZ",
	"EM",
	"EXE",
	"FA",
	"ISC",
	"ICN",
	"G",
	"INP",
	"PIE",
	"T20",
	"PYI",
	"PT",
	"Q",
	"RSE",
	"SLF",
	"SLOT",
	"SIM",
	"TID",
	"INT",
	"ARG",
	"PTH",
	"TD",
	"FIX",
	"ERA",
	"PD",
	"PL",
	"PERF",
	"FURB",
	"LOG",
	"RUF"

]
ignore = [
    "S101",
    "I001",
    "D100",
    "D400",
    "D415",
    "TD002",
    "TD003",
    "PT023",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
"test-integ/**.py" = [
    "D103",
    "ANN001",
    "ANN201",
    "PT004",
]
"test/**.py" = [
    "D103",
    "ANN001",
    "ANN201",
    "PT004",
    "PLR0913",
]


[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
