local map = vim.keymap.set

map("n", "<Leader>w<Leader>i", ":VimwikiDiaryGenerateLinks<CR>")
map("n", "<CR>", ":VimwikiFollowLink<CR>")
map("n", "<S-CR>", ":VimwikiSplitLink<CR>")
map("n", "<C-CR>", ":VimwikiVSplitLink<CR>")
map("n", "<Backspace>", ":VimwikiGoBackLink<CR>")
map("n", "<Tab>", ":VimwikiNextLink<CR>")
map("n", "<S-Tab>", ":VimwikiPrevLink<CR>")
map("n", "<Leader>wn", ":VimwikiGoto<CR>")
map("n", "<Leader>wd", ":VimwikiDeleteFile<CR>")
map("n", "<Leader>wr", ":VimwikiRenameFile<CR>")
map("n", "<C-Space>", ":VimwikiToggleListItem<CR>")
map("n", "<A-Left>", ":VimwikiTableMoveColumnLeft<CR>")
map("n", "<A-Right>", ":VimwikiTableMoveColumnRight<CR>")

map("n", "<2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("v", "<2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("i", "<2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("n", "<S-2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("v", "<S-2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("i", "<S-2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("n", "<C-2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("v", "<C-2-LeftMouse>", ":VimwikiFollowLink<CR>")
map("i", "<C-2-LeftMouse>", ":VimwikiFollowLink<CR>")

map("o", "a|", ":VimwikiTextObjTableCell<CR>")
map("v", "a|", ":VimwikiTextObjTableCellV<CR>")
map("o", "i|", ":VimwikiTextObjTableCellInner<CR>")
map("v", "i|", ":VimwikiTextObjTableCellInnerV<CR>")

map("o", "ac", ":VimwikiTextObjColumn<CR>")
map("v", "ac", ":VimwikiTextObjColumnV<CR>")
map("o", "ic", ":VimwikiTextObjColumnInner<CR>")
map("v", "ic", ":VimwikiTextObjColumnInnerV<CR>")
